# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftBaiduMapDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'BaiduMapKit', '~> 3.4.2' #百度地图SDK


  # Pods for SwiftBaiduMapDemo

  target 'SwiftBaiduMapDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftBaiduMapDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
